require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BloodGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # BloodGroup. As you add validations to BloodGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BloodGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all blood_groups as @blood_groups" do
      blood_group = BloodGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:blood_groups).should eq([blood_group])
    end
  end

  describe "GET show" do
    it "assigns the requested blood_group as @blood_group" do
      blood_group = BloodGroup.create! valid_attributes
      get :show, {:id => blood_group.to_param}, valid_session
      assigns(:blood_group).should eq(blood_group)
    end
  end

  describe "GET new" do
    it "assigns a new blood_group as @blood_group" do
      get :new, {}, valid_session
      assigns(:blood_group).should be_a_new(BloodGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested blood_group as @blood_group" do
      blood_group = BloodGroup.create! valid_attributes
      get :edit, {:id => blood_group.to_param}, valid_session
      assigns(:blood_group).should eq(blood_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BloodGroup" do
        expect {
          post :create, {:blood_group => valid_attributes}, valid_session
        }.to change(BloodGroup, :count).by(1)
      end

      it "assigns a newly created blood_group as @blood_group" do
        post :create, {:blood_group => valid_attributes}, valid_session
        assigns(:blood_group).should be_a(BloodGroup)
        assigns(:blood_group).should be_persisted
      end

      it "redirects to the created blood_group" do
        post :create, {:blood_group => valid_attributes}, valid_session
        response.should redirect_to(BloodGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved blood_group as @blood_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        BloodGroup.any_instance.stub(:save).and_return(false)
        post :create, {:blood_group => { "name" => "invalid value" }}, valid_session
        assigns(:blood_group).should be_a_new(BloodGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BloodGroup.any_instance.stub(:save).and_return(false)
        post :create, {:blood_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested blood_group" do
        blood_group = BloodGroup.create! valid_attributes
        # Assuming there are no other blood_groups in the database, this
        # specifies that the BloodGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BloodGroup.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => blood_group.to_param, :blood_group => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested blood_group as @blood_group" do
        blood_group = BloodGroup.create! valid_attributes
        put :update, {:id => blood_group.to_param, :blood_group => valid_attributes}, valid_session
        assigns(:blood_group).should eq(blood_group)
      end

      it "redirects to the blood_group" do
        blood_group = BloodGroup.create! valid_attributes
        put :update, {:id => blood_group.to_param, :blood_group => valid_attributes}, valid_session
        response.should redirect_to(blood_group)
      end
    end

    describe "with invalid params" do
      it "assigns the blood_group as @blood_group" do
        blood_group = BloodGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BloodGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => blood_group.to_param, :blood_group => { "name" => "invalid value" }}, valid_session
        assigns(:blood_group).should eq(blood_group)
      end

      it "re-renders the 'edit' template" do
        blood_group = BloodGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BloodGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => blood_group.to_param, :blood_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested blood_group" do
      blood_group = BloodGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => blood_group.to_param}, valid_session
      }.to change(BloodGroup, :count).by(-1)
    end

    it "redirects to the blood_groups list" do
      blood_group = BloodGroup.create! valid_attributes
      delete :destroy, {:id => blood_group.to_param}, valid_session
      response.should redirect_to(blood_groups_url)
    end
  end

end
