require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InsuranceCompaniesController do

  # This should return the minimal set of attributes required to create a valid
  # InsuranceCompany. As you add validations to InsuranceCompany, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InsuranceCompaniesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all insurance_companies as @insurance_companies" do
      insurance_company = InsuranceCompany.create! valid_attributes
      get :index, {}, valid_session
      assigns(:insurance_companies).should eq([insurance_company])
    end
  end

  describe "GET show" do
    it "assigns the requested insurance_company as @insurance_company" do
      insurance_company = InsuranceCompany.create! valid_attributes
      get :show, {:id => insurance_company.to_param}, valid_session
      assigns(:insurance_company).should eq(insurance_company)
    end
  end

  describe "GET new" do
    it "assigns a new insurance_company as @insurance_company" do
      get :new, {}, valid_session
      assigns(:insurance_company).should be_a_new(InsuranceCompany)
    end
  end

  describe "GET edit" do
    it "assigns the requested insurance_company as @insurance_company" do
      insurance_company = InsuranceCompany.create! valid_attributes
      get :edit, {:id => insurance_company.to_param}, valid_session
      assigns(:insurance_company).should eq(insurance_company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InsuranceCompany" do
        expect {
          post :create, {:insurance_company => valid_attributes}, valid_session
        }.to change(InsuranceCompany, :count).by(1)
      end

      it "assigns a newly created insurance_company as @insurance_company" do
        post :create, {:insurance_company => valid_attributes}, valid_session
        assigns(:insurance_company).should be_a(InsuranceCompany)
        assigns(:insurance_company).should be_persisted
      end

      it "redirects to the created insurance_company" do
        post :create, {:insurance_company => valid_attributes}, valid_session
        response.should redirect_to(InsuranceCompany.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved insurance_company as @insurance_company" do
        # Trigger the behavior that occurs when invalid params are submitted
        InsuranceCompany.any_instance.stub(:save).and_return(false)
        post :create, {:insurance_company => { "name" => "invalid value" }}, valid_session
        assigns(:insurance_company).should be_a_new(InsuranceCompany)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InsuranceCompany.any_instance.stub(:save).and_return(false)
        post :create, {:insurance_company => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested insurance_company" do
        insurance_company = InsuranceCompany.create! valid_attributes
        # Assuming there are no other insurance_companies in the database, this
        # specifies that the InsuranceCompany created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InsuranceCompany.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => insurance_company.to_param, :insurance_company => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested insurance_company as @insurance_company" do
        insurance_company = InsuranceCompany.create! valid_attributes
        put :update, {:id => insurance_company.to_param, :insurance_company => valid_attributes}, valid_session
        assigns(:insurance_company).should eq(insurance_company)
      end

      it "redirects to the insurance_company" do
        insurance_company = InsuranceCompany.create! valid_attributes
        put :update, {:id => insurance_company.to_param, :insurance_company => valid_attributes}, valid_session
        response.should redirect_to(insurance_company)
      end
    end

    describe "with invalid params" do
      it "assigns the insurance_company as @insurance_company" do
        insurance_company = InsuranceCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InsuranceCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => insurance_company.to_param, :insurance_company => { "name" => "invalid value" }}, valid_session
        assigns(:insurance_company).should eq(insurance_company)
      end

      it "re-renders the 'edit' template" do
        insurance_company = InsuranceCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InsuranceCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => insurance_company.to_param, :insurance_company => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested insurance_company" do
      insurance_company = InsuranceCompany.create! valid_attributes
      expect {
        delete :destroy, {:id => insurance_company.to_param}, valid_session
      }.to change(InsuranceCompany, :count).by(-1)
    end

    it "redirects to the insurance_companies list" do
      insurance_company = InsuranceCompany.create! valid_attributes
      delete :destroy, {:id => insurance_company.to_param}, valid_session
      response.should redirect_to(insurance_companies_url)
    end
  end

end
