require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MedicamentsController do

  # This should return the minimal set of attributes required to create a valid
  # Medicament. As you add validations to Medicament, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MedicamentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all medicaments as @medicaments" do
      medicament = Medicament.create! valid_attributes
      get :index, {}, valid_session
      assigns(:medicaments).should eq([medicament])
    end
  end

  describe "GET show" do
    it "assigns the requested medicament as @medicament" do
      medicament = Medicament.create! valid_attributes
      get :show, {:id => medicament.to_param}, valid_session
      assigns(:medicament).should eq(medicament)
    end
  end

  describe "GET new" do
    it "assigns a new medicament as @medicament" do
      get :new, {}, valid_session
      assigns(:medicament).should be_a_new(Medicament)
    end
  end

  describe "GET edit" do
    it "assigns the requested medicament as @medicament" do
      medicament = Medicament.create! valid_attributes
      get :edit, {:id => medicament.to_param}, valid_session
      assigns(:medicament).should eq(medicament)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Medicament" do
        expect {
          post :create, {:medicament => valid_attributes}, valid_session
        }.to change(Medicament, :count).by(1)
      end

      it "assigns a newly created medicament as @medicament" do
        post :create, {:medicament => valid_attributes}, valid_session
        assigns(:medicament).should be_a(Medicament)
        assigns(:medicament).should be_persisted
      end

      it "redirects to the created medicament" do
        post :create, {:medicament => valid_attributes}, valid_session
        response.should redirect_to(Medicament.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved medicament as @medicament" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medicament.any_instance.stub(:save).and_return(false)
        post :create, {:medicament => { "name" => "invalid value" }}, valid_session
        assigns(:medicament).should be_a_new(Medicament)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medicament.any_instance.stub(:save).and_return(false)
        post :create, {:medicament => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested medicament" do
        medicament = Medicament.create! valid_attributes
        # Assuming there are no other medicaments in the database, this
        # specifies that the Medicament created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Medicament.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => medicament.to_param, :medicament => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested medicament as @medicament" do
        medicament = Medicament.create! valid_attributes
        put :update, {:id => medicament.to_param, :medicament => valid_attributes}, valid_session
        assigns(:medicament).should eq(medicament)
      end

      it "redirects to the medicament" do
        medicament = Medicament.create! valid_attributes
        put :update, {:id => medicament.to_param, :medicament => valid_attributes}, valid_session
        response.should redirect_to(medicament)
      end
    end

    describe "with invalid params" do
      it "assigns the medicament as @medicament" do
        medicament = Medicament.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medicament.any_instance.stub(:save).and_return(false)
        put :update, {:id => medicament.to_param, :medicament => { "name" => "invalid value" }}, valid_session
        assigns(:medicament).should eq(medicament)
      end

      it "re-renders the 'edit' template" do
        medicament = Medicament.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medicament.any_instance.stub(:save).and_return(false)
        put :update, {:id => medicament.to_param, :medicament => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested medicament" do
      medicament = Medicament.create! valid_attributes
      expect {
        delete :destroy, {:id => medicament.to_param}, valid_session
      }.to change(Medicament, :count).by(-1)
    end

    it "redirects to the medicaments list" do
      medicament = Medicament.create! valid_attributes
      delete :destroy, {:id => medicament.to_param}, valid_session
      response.should redirect_to(medicaments_url)
    end
  end

end
