require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PacientsController do

  # This should return the minimal set of attributes required to create a valid
  # Pacient. As you add validations to Pacient, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "lastname" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PacientsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pacients as @pacients" do
      pacient = Pacient.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pacients).should eq([pacient])
    end
  end

  describe "GET show" do
    it "assigns the requested pacient as @pacient" do
      pacient = Pacient.create! valid_attributes
      get :show, {:id => pacient.to_param}, valid_session
      assigns(:pacient).should eq(pacient)
    end
  end

  describe "GET new" do
    it "assigns a new pacient as @pacient" do
      get :new, {}, valid_session
      assigns(:pacient).should be_a_new(Pacient)
    end
  end

  describe "GET edit" do
    it "assigns the requested pacient as @pacient" do
      pacient = Pacient.create! valid_attributes
      get :edit, {:id => pacient.to_param}, valid_session
      assigns(:pacient).should eq(pacient)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pacient" do
        expect {
          post :create, {:pacient => valid_attributes}, valid_session
        }.to change(Pacient, :count).by(1)
      end

      it "assigns a newly created pacient as @pacient" do
        post :create, {:pacient => valid_attributes}, valid_session
        assigns(:pacient).should be_a(Pacient)
        assigns(:pacient).should be_persisted
      end

      it "redirects to the created pacient" do
        post :create, {:pacient => valid_attributes}, valid_session
        response.should redirect_to(Pacient.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pacient as @pacient" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pacient.any_instance.stub(:save).and_return(false)
        post :create, {:pacient => { "lastname" => "invalid value" }}, valid_session
        assigns(:pacient).should be_a_new(Pacient)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pacient.any_instance.stub(:save).and_return(false)
        post :create, {:pacient => { "lastname" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pacient" do
        pacient = Pacient.create! valid_attributes
        # Assuming there are no other pacients in the database, this
        # specifies that the Pacient created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pacient.any_instance.should_receive(:update_attributes).with({ "lastname" => "MyString" })
        put :update, {:id => pacient.to_param, :pacient => { "lastname" => "MyString" }}, valid_session
      end

      it "assigns the requested pacient as @pacient" do
        pacient = Pacient.create! valid_attributes
        put :update, {:id => pacient.to_param, :pacient => valid_attributes}, valid_session
        assigns(:pacient).should eq(pacient)
      end

      it "redirects to the pacient" do
        pacient = Pacient.create! valid_attributes
        put :update, {:id => pacient.to_param, :pacient => valid_attributes}, valid_session
        response.should redirect_to(pacient)
      end
    end

    describe "with invalid params" do
      it "assigns the pacient as @pacient" do
        pacient = Pacient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pacient.any_instance.stub(:save).and_return(false)
        put :update, {:id => pacient.to_param, :pacient => { "lastname" => "invalid value" }}, valid_session
        assigns(:pacient).should eq(pacient)
      end

      it "re-renders the 'edit' template" do
        pacient = Pacient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pacient.any_instance.stub(:save).and_return(false)
        put :update, {:id => pacient.to_param, :pacient => { "lastname" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pacient" do
      pacient = Pacient.create! valid_attributes
      expect {
        delete :destroy, {:id => pacient.to_param}, valid_session
      }.to change(Pacient, :count).by(-1)
    end

    it "redirects to the pacients list" do
      pacient = Pacient.create! valid_attributes
      delete :destroy, {:id => pacient.to_param}, valid_session
      response.should redirect_to(pacients_url)
    end
  end

end
