require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TreatmentTypesController do

  # This should return the minimal set of attributes required to create a valid
  # TreatmentType. As you add validations to TreatmentType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TreatmentTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all treatment_types as @treatment_types" do
      treatment_type = TreatmentType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:treatment_types).should eq([treatment_type])
    end
  end

  describe "GET show" do
    it "assigns the requested treatment_type as @treatment_type" do
      treatment_type = TreatmentType.create! valid_attributes
      get :show, {:id => treatment_type.to_param}, valid_session
      assigns(:treatment_type).should eq(treatment_type)
    end
  end

  describe "GET new" do
    it "assigns a new treatment_type as @treatment_type" do
      get :new, {}, valid_session
      assigns(:treatment_type).should be_a_new(TreatmentType)
    end
  end

  describe "GET edit" do
    it "assigns the requested treatment_type as @treatment_type" do
      treatment_type = TreatmentType.create! valid_attributes
      get :edit, {:id => treatment_type.to_param}, valid_session
      assigns(:treatment_type).should eq(treatment_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TreatmentType" do
        expect {
          post :create, {:treatment_type => valid_attributes}, valid_session
        }.to change(TreatmentType, :count).by(1)
      end

      it "assigns a newly created treatment_type as @treatment_type" do
        post :create, {:treatment_type => valid_attributes}, valid_session
        assigns(:treatment_type).should be_a(TreatmentType)
        assigns(:treatment_type).should be_persisted
      end

      it "redirects to the created treatment_type" do
        post :create, {:treatment_type => valid_attributes}, valid_session
        response.should redirect_to(TreatmentType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved treatment_type as @treatment_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        TreatmentType.any_instance.stub(:save).and_return(false)
        post :create, {:treatment_type => { "name" => "invalid value" }}, valid_session
        assigns(:treatment_type).should be_a_new(TreatmentType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TreatmentType.any_instance.stub(:save).and_return(false)
        post :create, {:treatment_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested treatment_type" do
        treatment_type = TreatmentType.create! valid_attributes
        # Assuming there are no other treatment_types in the database, this
        # specifies that the TreatmentType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TreatmentType.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => treatment_type.to_param, :treatment_type => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested treatment_type as @treatment_type" do
        treatment_type = TreatmentType.create! valid_attributes
        put :update, {:id => treatment_type.to_param, :treatment_type => valid_attributes}, valid_session
        assigns(:treatment_type).should eq(treatment_type)
      end

      it "redirects to the treatment_type" do
        treatment_type = TreatmentType.create! valid_attributes
        put :update, {:id => treatment_type.to_param, :treatment_type => valid_attributes}, valid_session
        response.should redirect_to(treatment_type)
      end
    end

    describe "with invalid params" do
      it "assigns the treatment_type as @treatment_type" do
        treatment_type = TreatmentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TreatmentType.any_instance.stub(:save).and_return(false)
        put :update, {:id => treatment_type.to_param, :treatment_type => { "name" => "invalid value" }}, valid_session
        assigns(:treatment_type).should eq(treatment_type)
      end

      it "re-renders the 'edit' template" do
        treatment_type = TreatmentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TreatmentType.any_instance.stub(:save).and_return(false)
        put :update, {:id => treatment_type.to_param, :treatment_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested treatment_type" do
      treatment_type = TreatmentType.create! valid_attributes
      expect {
        delete :destroy, {:id => treatment_type.to_param}, valid_session
      }.to change(TreatmentType, :count).by(-1)
    end

    it "redirects to the treatment_types list" do
      treatment_type = TreatmentType.create! valid_attributes
      delete :destroy, {:id => treatment_type.to_param}, valid_session
      response.should redirect_to(treatment_types_url)
    end
  end

end
